### ISSUE TITLE
Failing to launch gaia as a simple deployment in rancher (kubernetes)

### ISSUE THREAD

**Issue by arthurlogilab** [gaia-pipeline/gaia#263]
While trying to run the docker image manually in our rancher instance (which connects to our kubernetes instance) I get the following error : 

```
2020-06-25T10:56:44.771Z [WARN ] Gaia: using auto-generated key to sign jwt tokens, do not use in production
2020-06-25T10:56:44.877Z [INFO ] Gaia: worker gRPC server about to start on port: 8989
2020-06-25T10:56:44.899Z [ERROR] Gaia: failed to start echo listener: error="listen tcp: address :tcp://10.43.51.83:80: too many colons in address"
2020-06-25T10:56:44.901Z [INFO ] Gaia: exit signal received. Exiting...
```

When I remove the port mapping, the image runs fine but I can't contact it. Is there some code in gaia that looks at the way the port mapping is defined and parses that and fails here ? If you are familiar with rancher I've tried a number of variations with NodePort, HostPort and ClusterIP but it always fails.

**Comment by Skarlso** [comment]
Hi!

yes, I also experience this. This is some weird thing going on in Kubernetes... The service needs to exists AFTER the server has started. Somehow they collide. I didn't have the time to investigate this in greater detail yet... But basically I have to kill the service and then update gaia and initiate the service again. Now, this results in a few seconds of downtime of course, which is not ideal. :/ But I haven't found a workaround yet.

**Comment by Skarlso** [comment]
So I think I found the problem. It has something to do with colliding environment names with the kubernetes generated environment names. It collides with the service defined port names and parses the wrong value.

I'll have a fix soonish. :)

**Comment by Skarlso** [comment]
@arthurlogilab The fix is to not call the service OR the deployment `gaia` because that's the prefix for the gaia environment properties. So when GAIA_PORT is created inside the POD because of Kubernetes, it takes over what Gaia set. :)

In the long run I'll rename what Gaia is using as a prefix for environment properties. But for now, please use a different name. :)

**Comment by arthurlogilab** [comment]
@Skarlso glad you found the origin of the bug. Thanks for looking into it ! Can you think of a workaround that could be applied (for example forcing a variable to a given value to override the k8 generated value) ?

**Comment by Skarlso** [comment]
@arthurlogilab the workaround is not to call your service or the deployment in kubernetes `gaia`. :) 

For example:
```yaml
kind: Service
apiVersion: v1
metadata:
  namespace: cronohub
  name: gaia-svc
  labels:
    app: gaia-svc
    app.kubernetes.io/name: gaia-svc
    app.kubernetes.io/instance: gaia-svc
spec:
  selector:
    app: gaia-app
    app.kubernetes.io/name: gaia-app
    app.kubernetes.io/instance: gaia-app
  ports:
  - name: http
    port: 8080
    targetPort: gaia-http
```

This is good.

This is bad:
```yaml
kind: Service
apiVersion: v1
metadata:
  namespace: cronohub
  name: gaia
  labels:
    app: gaia
    app.kubernetes.io/name: gaia
    app.kubernetes.io/instance: gaia
spec:
  selector:
    app: gaia-app
    app.kubernetes.io/name: gaia-app
    app.kubernetes.io/instance: gaia-app
  ports:
  - name: http
    port: 8080
    targetPort: gaia-http
```
